### ISSUE TITLE
Blaze adds all Unarchived Verifications, even though most will have been already added.

### ISSUE THREAD

**Issue by kayabaNerve** [EmberCrypto/Blaze#2]
I'm thinking we utilize a table of string (serialized Verification, not MemoryVerification) -> bool to check if it's already added.

**Comment by Mistersx12** [comment]
MemoryVerification, Memory Verification

**Comment by kayabaNerve** [comment]
@Mistersx12 Why did you leave this comment?

**Comment by Mistersx12** [comment]
I saw that the names was together, and I was thinking it's important to you
